import { tokens } from "../theme";
import type { CSSProperties } from "react";

export const efficiencyCurveStyles: Record<string, CSSProperties> = {
  container: {
    flex: 1,
    minHeight: 0,
    display: "flex",
    flexDirection: "column",
    padding: `${tokens.sp3}px ${tokens.sp6}px ${tokens.sp4}px`,
    overflow: "hidden",
    background: tokens.surface0,
  },
  title: {
    fontSize: tokens.fsBody,
    fontWeight: 600,
    color: tokens.muted,
    fontFamily: tokens.fontMono,
    marginBottom: tokens.sp2,
  },
  metricTabs: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr 1fr",
    gap: tokens.sp2,
    marginBottom: tokens.sp2,
  },
  metricTab: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    gap: 3,
    padding: `${tokens.sp2}px ${tokens.sp3}px`,
    borderRadius: tokens.radiusSm,
    borderLeft: `3px solid transparent`,
    border: `1px solid ${tokens.surface2}`,
    borderLeftWidth: 3,
    cursor: "pointer",
    textAlign: "left" as const,
    transition: "background 0.15s, border-color 0.15s",
    fontFamily: tokens.fontMono,
  },
  metricTabLabel: {
    fontSize: tokens.fsBody,
    fontWeight: 600,
    letterSpacing: "-0.01em",
  },
  metricTabSignal: {
    fontSize: tokens.fsMicro,
    lineHeight: 1.4,
    fontStyle: "italic",
  },
  signalBar: {
    display: "flex",
    flexDirection: "column",
    gap: 2,
    padding: `${tokens.sp2}px ${tokens.sp3}px`,
    background: tokens.surface1,
    borderRadius: tokens.radiusSm,
    marginBottom: tokens.sp2,
    borderLeft: `1px solid ${tokens.border}`,
  },
  signalFormula: {
    fontSize: tokens.fsMicro,
    color: tokens.text,
    fontFamily: tokens.fontMono,
    letterSpacing: "0.01em",
  },
  signalWatch: {
    fontSize: tokens.fsMicro,
    color: tokens.muted,
    fontFamily: tokens.fontMono,
  },
  legend: {
    display: "flex",
    alignItems: "center",
    gap: 20,
    marginBottom: tokens.sp2,
  },
  legendItem: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    fontSize: tokens.fsMicro,
    color: tokens.muted,
    fontFamily: tokens.fontMono,
  },
  legendDot: {
    width: 7,
    height: 7,
    borderRadius: "50%",
    flexShrink: 0,
  },
  empty: {
    flex: 1,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: tokens.muted,
    fontSize: tokens.fsBody,
    fontFamily: tokens.fontMono,
  },
};
