import { tokens, gc } from "../../theme";
import type { CSSProperties } from "react";

export const memoryStyles: Record<string, CSSProperties> = {
  panel: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    width: 520,
    background: tokens.surface0,
    borderLeft: `0.5px solid ${tokens.border}`,
    display: "flex",
    flexDirection: "column",
    zIndex: 10,
    overflow: "hidden",
  },
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: `${tokens.sp3}px ${tokens.sp4}px`,
    borderBottom: `0.5px solid ${tokens.border}`,
    flexShrink: 0,
  },
  headerLeft: {
    display: "flex",
    alignItems: "center",
    gap: tokens.sp3,
  },
  headerIcon: {
    fontSize: 20,
    color: gc.soft_gc.text,
    fontFamily: tokens.fontMono,
  },
  headerTitle: {
    fontSize: tokens.fsBody,
    fontWeight: 600,
    color: tokens.highlight,
    fontFamily: tokens.fontMono,
  },
  headerSub: {
    fontSize: tokens.fsMicro,
    color: tokens.muted,
    fontFamily: tokens.fontMono,
  },
  closeBtn: {
    background: "none",
    border: "none",
    color: tokens.muted,
    cursor: "pointer",
    fontSize: tokens.fsBody,
    fontFamily: tokens.fontMono,
    padding: 0,
  },
  tabRow: {
    display: "flex",
    alignItems: "center",
    borderBottom: `0.5px solid ${tokens.border}`,
    flexShrink: 0,
  },
  tab: {
    background: "transparent",
    border: "none",
    borderBottom: "2px solid transparent",
    color: tokens.muted,
    cursor: "pointer",
    fontSize: tokens.fsData,
    fontFamily: tokens.fontMono,
    padding: `${tokens.sp2}px ${tokens.sp4}px`,
    display: "flex",
    alignItems: "center",
    gap: tokens.sp1,
  },
  tabActive: {
    color: tokens.highlight,
    borderBottomColor: gc.soft_gc.text,
  },
  tabBadge: {
    background: tokens.surface2,
    borderRadius: tokens.radiusPill,
    color: tokens.muted,
    fontSize: tokens.fsMicro,
    fontFamily: tokens.fontMono,
    padding: "1px 5px",
  },
  refreshBtn: {
    marginLeft: "auto",
    marginRight: tokens.sp3,
    background: "transparent",
    border: "none",
    color: tokens.muted,
    cursor: "pointer",
    fontSize: tokens.fsBody,
    fontFamily: tokens.fontMono,
  },
  body: {
    flex: 1,
    overflowY: "auto",
    padding: tokens.sp3,
  },
  empty: {
    padding: `${tokens.sp10}px ${tokens.sp4}px`,
    textAlign: "center",
    color: tokens.muted,
    fontSize: tokens.fsData,
    fontFamily: tokens.fontMono,
  },
  fileCard: {
    background: tokens.surface1,
    border: `0.5px solid ${tokens.border}`,
    borderRadius: tokens.radiusSm,
    marginBottom: tokens.sp2,
    overflow: "hidden",
  },
  fileCardHeader: {
    display: "flex",
    alignItems: "center",
    gap: tokens.sp2,
    padding: `${tokens.sp2}px ${tokens.sp3}px`,
    background: "transparent",
    border: "none",
    width: "100%",
    cursor: "pointer",
    textAlign: "left",
  },
  fileIcon: {
    fontSize: tokens.fsMicro,
    color: gc.soft_gc.text,
    flexShrink: 0,
  },
  fileName: {
    fontSize: tokens.fsData,
    color: tokens.highlight,
    fontFamily: tokens.fontMono,
    flex: 1,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  fileMeta: {
    fontSize: tokens.fsMicro,
    color: tokens.muted,
    fontFamily: tokens.fontMono,
    fontVariantNumeric: "tabular-nums",
    flexShrink: 0,
  },
  chevron: {
    fontSize: tokens.fsMicro,
    color: tokens.muted,
    fontFamily: tokens.fontMono,
    flexShrink: 0,
    marginLeft: tokens.sp1,
  },
  fileContent: {
    margin: 0,
    padding: `${tokens.sp2}px ${tokens.sp3}px`,
    borderTop: `0.5px solid ${tokens.border}`,
    fontSize: tokens.fsMicro,
    color: tokens.text,
    fontFamily: tokens.fontMono,
    lineHeight: 1.7,
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
    overflowY: "auto",
    maxHeight: 400,
    background: tokens.surface2,
  },
  // History layout
  historyLayout: {
    display: "flex",
    gap: tokens.sp3,
    height: "100%",
    minHeight: 0,
  },
  timeline: {
    width: 148,
    flexShrink: 0,
    display: "flex",
    flexDirection: "column",
    gap: 2,
  },
  timelineItem: {
    display: "flex",
    alignItems: "flex-start",
    gap: tokens.sp2,
    padding: `${tokens.sp2}px ${tokens.sp2}px`,
    background: "transparent",
    border: `0.5px solid transparent`,
    borderRadius: tokens.radiusSm,
    cursor: "pointer",
    textAlign: "left",
  },
  timelineItemActive: {
    background: tokens.surface1,
    border: `0.5px solid ${tokens.border}`,
  },
  timelineDot: {
    width: 6,
    height: 6,
    borderRadius: "50%",
    background: gc.soft_gc.dot,
    flexShrink: 0,
    marginTop: 4,
  },
  timelineText: {
    flex: 1,
    minWidth: 0,
  },
  timelineDate: {
    fontSize: tokens.fsMicro,
    color: tokens.text,
    fontFamily: tokens.fontMono,
    lineHeight: 1.4,
  },
  timelineMeta: {
    fontSize: tokens.fsMicro,
    color: tokens.muted,
    fontFamily: tokens.fontMono,
    fontVariantNumeric: "tabular-nums",
    lineHeight: 1.4,
  },
  diffPane: {
    flex: 1,
    minWidth: 0,
  },
  diffBadge: {
    fontSize: tokens.fsMicro,
    fontFamily: tokens.fontMono,
    borderRadius: tokens.radiusPill,
    padding: "1px 5px",
    flexShrink: 0,
  },
  diffBody: {
    borderTop: `0.5px solid ${tokens.border}`,
    maxHeight: 320,
    overflowY: "auto",
    background: tokens.surface2,
  },
  diffLine: {
    display: "flex",
    gap: tokens.sp2,
    padding: "1px 0",
    fontFamily: tokens.fontMono,
    fontSize: tokens.fsMicro,
    lineHeight: 1.6,
  },
  diffAdded: {
    background: `${gc.clean.bg}`,
    color: gc.clean.text,
  },
  diffRemoved: {
    background: `${gc.hard_gc.bg}`,
    color: gc.hard_gc.text,
    textDecoration: "line-through",
    opacity: 0.7,
  },
  diffGutter: {
    width: 16,
    flexShrink: 0,
    textAlign: "right",
    color: tokens.muted,
    userSelect: "none",
    paddingRight: tokens.sp1,
  },
};
