import type { CSSProperties } from "react";

export const sessionItemStyles: Record<string, CSSProperties> = {
  container: {
    width: 240,
    borderRight: "1px solid #2c2c2e",
    overflowY: "auto",
    flexShrink: 0,
    background: "#111113",
    display: "flex",
    flexDirection: "column",
  },
  header: {
    padding: "10px 12px 8px",
    borderBottom: "1px solid #2c2c2e",
    background: "#111113",
    position: "sticky",
    top: 0,
    zIndex: 1,
  },
  headerLabel: {
    fontSize: 11,
    fontWeight: 600,
    letterSpacing: "0.08em",
    textTransform: "uppercase" as const,
    color: "#636366",
    display: "block",
    marginBottom: 8,
  },
  tabs: {
    display: "flex",
    gap: 2,
  },
  tab: {
    flex: 1,
    padding: "4px 0",
    fontSize: 10,
    fontFamily: "monospace",
    background: "transparent",
    border: "1px solid #2c2c2e",
    borderRadius: 4,
    color: "#48484a",
    cursor: "pointer",
    letterSpacing: "0.03em",
  },
  tabActive: {
    background: "#2c2c2e",
    color: "#f2f2f7",
    borderColor: "#3a3a3c",
  },
  empty: {
    padding: 16,
    color: "#48484a",
    fontSize: 12,
    fontFamily: "monospace",
  },
  groupHeader: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    width: "100%",
    padding: "8px 12px",
    background: "transparent",
    border: "none",
    borderBottom: "1px solid #1c1c1e",
    cursor: "pointer",
    textAlign: "left" as const,
  },
  chevron: {
    fontSize: 9,
    color: "#48484a",
    flexShrink: 0,
    width: 10,
  },
  groupName: {
    flex: 1,
    fontSize: 12,
    fontWeight: 600,
    color: "#aeaeb2",
    fontFamily: "monospace",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  groupMeta: {
    fontSize: 10,
    color: "#48484a",
    fontFamily: "monospace",
    marginRight: 4,
  },
  groupCost: {
    fontSize: 11,
    color: "#8e8e93",
    fontFamily: "monospace",
    fontVariantNumeric: "tabular-nums",
    marginRight: 6,
  },
  groupPct: {
    fontSize: 11,
    fontWeight: 600,
    fontFamily: "monospace",
    fontVariantNumeric: "tabular-nums",
  },
  rankedRow: {
    display: "flex",
    alignItems: "stretch",
    borderBottom: "1px solid #1c1c1e",
  },
  rank: {
    width: 32,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 10,
    color: "#48484a",
    fontFamily: "monospace",
    flexShrink: 0,
    borderRight: "1px solid #1c1c1e",
  },
  row: {
    display: "block",
    width: "100%",
    padding: "10px 14px",
    background: "transparent",
    border: "none",
    borderBottom: "1px solid #1c1c1e",
    cursor: "pointer",
    textAlign: "left" as const,
    transition: "background 0.1s",
  },
  rowSelected: {
    background: "#1c1c1e",
  },
  rowTop: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    marginBottom: 4,
  },
  dot: {
    width: 7,
    height: 7,
    borderRadius: "50%",
    flexShrink: 0,
  },
  name: {
    flex: 1,
    color: "#f2f2f7",
    fontSize: 13,
    fontWeight: 500,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  pct: {
    fontSize: 12,
    fontWeight: 600,
    fontVariantNumeric: "tabular-nums",
  },
  rowBottom: {
    display: "flex",
    justifyContent: "space-between",
    marginBottom: 7,
  },
  meta: {
    color: "#48484a",
    fontSize: 11,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  metaCost: {
    color: "#8e8e93",
    fontSize: 11,
    fontVariantNumeric: "tabular-nums",
    flexShrink: 0,
    marginLeft: 6,
  },
  track: {
    height: 2,
    background: "#2c2c2e",
    borderRadius: 1,
    overflow: "hidden",
  },
  fill: {
    height: "100%",
    borderRadius: 1,
    transition: "width 0.4s ease",
  },
};
