import { tokens, gc } from "../../theme.js";
import type { CSSProperties } from "react";

// ── Styles ────────────────────────────────────────────────────────────────────
export const SANS =
  "-apple-system, BlinkMacSystemFont, 'SF Pro Display', 'SF Pro Text', system-ui, sans-serif";

export const projectSessionTreeStyles: Record<string, CSSProperties> = {
  container: {
    flex: 1,
    overflowY: "auto",
    background: tokens.void,
  },
  empty: {
    padding: "48px 32px",
    textAlign: "center",
    color: tokens.muted,
    fontSize: tokens.fsBody,
    fontFamily: tokens.fontMono,
    lineHeight: 1.8,
  },
  // Groups get a clear visual break — heavier border between projects
  group: {
    borderBottom: `1px solid ${tokens.border}`,
  },
  projectHeader: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "12px 20px",
    minHeight: 48,
    background: tokens.surface0,
    cursor: "pointer",
    userSelect: "none",
    position: "sticky" as const,
    top: 0,
    zIndex: 1,
    borderBottom: `0.5px solid ${tokens.surface1}`,
  },
  chevron: {
    color: tokens.muted,
    fontSize: 10,
    transition: "transform 0.15s ease",
    flexShrink: 0,
    lineHeight: 1,
  },
  // Topology label — marks this row as the project (vs. session) altitude
  projectKindTag: {
    fontSize: 8,
    fontWeight: 700,
    letterSpacing: "0.12em",
    color: tokens.muted,
    background: tokens.surface2,
    borderRadius: tokens.radiusXs,
    padding: "2px 5px",
    flexShrink: 0,
  },
  projectDot: {
    width: 8,
    height: 8,
    borderRadius: "50%",
    flexShrink: 0,
  },
  // Project names use system UI — they're labels, not data
  projectName: {
    fontSize: 14,
    fontWeight: 600,
    color: tokens.highlight,
    fontFamily: SANS,
    letterSpacing: "-0.01em",
    flex: 1,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  projectCount: {
    fontSize: tokens.fsMicro,
    color: tokens.muted,
    fontFamily: tokens.fontMono,
    flexShrink: 0,
    letterSpacing: "0.02em",
  },
  gcChip: {
    fontSize: tokens.fsMicro,
    padding: "3px 8px",
    borderRadius: tokens.radiusSm,
    fontFamily: tokens.fontMono,
    fontWeight: 500,
    letterSpacing: "0.04em",
    flexShrink: 0,
  },
  // Policy banner — sits between project header and its sessions
  policyBanner: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "7px 12px 7px 0",
    background: tokens.void,
    borderBottom: `0.5px solid ${tokens.surface1}`,
    minHeight: 34,
  },
  policyStatusDot: {
    width: 6,
    height: 6,
    borderRadius: "50%",
    flexShrink: 0,
  },
  policyStatusText: {
    fontSize: tokens.fsMicro,
    fontFamily: tokens.fontMono,
    letterSpacing: "0.03em",
    flex: 1,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  policyActions: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    flexShrink: 0,
  },
  editPolicyBtn: {
    background: tokens.surface2,
    border: `0.5px solid ${tokens.border}`,
    borderRadius: tokens.radiusSm,
    color: tokens.highlight,
    fontSize: tokens.fsMicro,
    fontFamily: tokens.fontMono,
    fontWeight: 500,
    letterSpacing: "0.03em",
    cursor: "pointer",
    padding: "4px 10px",
    lineHeight: 1,
  },
  // Flat-list header for session view
  flatHeader: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "12px 20px",
    minHeight: 44,
    background: tokens.surface0,
    position: "sticky" as const,
    top: 0,
    zIndex: 1,
    borderBottom: `0.5px solid ${tokens.border}`,
  },
  flatHeaderLabel: {
    fontSize: 14,
    fontWeight: 600,
    color: tokens.highlight,
    fontFamily: SANS,
    letterSpacing: "-0.01em",
    flex: 1,
  },
  flatHeaderCount: {
    fontSize: tokens.fsMicro,
    color: tokens.muted,
    fontFamily: tokens.fontMono,
    letterSpacing: "0.02em",
  },
  sessionRow: {
    display: "grid",
    gridTemplateColumns: "1fr 140px 48px 80px 72px 36px",
    alignItems: "center",
    gap: 12,
    padding: "10px 20px 10px 0",
    borderBottom: `0.5px solid ${tokens.surface1}`,
    cursor: "pointer",
    transition: "background 0.15s",
    minHeight: 40,
  },
  sessionRowSelected: {
    background: tokens.surface2,
  },
  sessionLeft: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    overflow: "hidden",
    paddingLeft: 4,
  },
  indent: {
    width: 32,
    flexShrink: 0,
  },
  dot: {
    width: 7,
    height: 7,
    borderRadius: "50%",
    flexShrink: 0,
  },
  // Session names: system UI for readability, mono only for IDs and data
  sessionName: {
    fontSize: tokens.fsBody,
    fontWeight: 500,
    fontFamily: SANS,
    letterSpacing: "-0.01em",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  // Project provenance tag — only shown in flat session view
  projectTag: {
    fontSize: tokens.fsMicro,
    color: tokens.muted,
    fontFamily: tokens.fontMono,
    background: tokens.surface1,
    border: `0.5px solid ${tokens.surface2}`,
    borderRadius: tokens.radiusXs,
    padding: "1px 6px",
    flexShrink: 0,
    maxWidth: 140,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  sessionId: {
    color: tokens.border,
    fontSize: tokens.fsMicro,
    fontFamily: tokens.fontMono,
    flexShrink: 0,
  },
  barWrap: {
    display: "flex",
    alignItems: "center",
  },
  barTrack: {
    position: "relative",
    width: "100%",
    height: 4,
    background: tokens.surface2,
    borderRadius: 999,
    overflow: "hidden",
  },
  barFill: {
    position: "absolute",
    top: 0,
    left: 0,
    height: "100%",
    borderRadius: 999,
    transition: "width 0.4s ease",
    zIndex: 1,
  },
  barZone: {
    position: "absolute",
    top: 0,
    width: "20%",
    height: "100%",
  },
  pct: {
    fontSize: tokens.fsData,
    fontFamily: tokens.fontMono,
    fontWeight: 600,
    textAlign: "right",
    fontVariantNumeric: "tabular-nums",
  },
  time: {
    fontSize: tokens.fsMicro,
    color: tokens.muted,
    fontFamily: tokens.fontMono,
    textAlign: "right",
    fontVariantNumeric: "tabular-nums",
  },
  staleToggle: {
    display: "block",
    width: "100%",
    padding: "7px 20px 7px 56px",
    background: "transparent",
    border: "none",
    borderBottom: `0.5px solid ${tokens.surface1}`,
    color: tokens.muted,
    fontSize: tokens.fsMicro,
    fontFamily: tokens.fontMono,
    cursor: "pointer",
    textAlign: "left" as const,
    letterSpacing: "0.04em",
  },
  forkBadge: {
    fontSize: tokens.fsMicro,
    color: gc.soft_gc.text,
    fontFamily: tokens.fontMono,
    opacity: 0.8,
    flexShrink: 0,
  },
  rowActions: {
    display: "flex",
    justifyContent: "flex-end",
  },
};
